project_name: ghaction
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - amd64
dockers:
  - dockerfile: Dockerfile
    skip_push: auto
    image_templates:
      - "ghcr.io/tiero/ghaction:{{ .Version }}"
      - "ghcr.io/tiero/ghaction:latest"
  - dockerfile: Dockerfile
    skip_push: false
    image_templates:
      - "ghcr.io/tiero/ghaction:{{ .Version }}"
